apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rx9j2yk0a-python 
  janus-idp.io/tekton: rx9j2yk0a-python
  backstage.io/kubernetes-id: rx9j2yk0a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rx9j2yk0a-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  