apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rx9j2yk0a-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rx9j2yk0a-python 
  name: rx9j2yk0a-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rx9j2yk0a-python 
